apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicheck-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicheck
  template:
    metadata:
      labels:
        app: apicheck
    spec:
      containers:
      - name: apicheck
        image: (Se coloca la imagen del Docker)